version: "3.1"
services:
  bell:
    container_name: bell
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - CONFIGS=sparow,test-auth-token,http://sparow_core/api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - 5002:5002
      - 5003:5003
    stdin_open: true
    tty: true
networks:
  default:
    external:
      name: salimon
