name: bell
services:
  bell:
    public: true
    image: docker.io/salimondev/bell
    build: bell
    replicas: 1
    ports:
      - 5003
      - 5002
    resources:
      cpu: 100m
      memory: 128Mi
