on: push
name: example
jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Build"
      uses: okteto/build@master
      with:
        tag: registry.cloud.okteto.net/mr-exception/bell:${{ github.sha }}
        file: Dockerfile.production