name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Build
        uses: okteto/actions/build@v1
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          tag: registry.cloud.okteto.net/mr-exception/bell:${{ github.sha }}
