on: push
name: deploy
jobs:
  okteto:
    runs-on: ubuntu-latest
    steps:
      - name: install okteto
        run: curl https://get.okteto.com -sSfL | sh
      - name: install okteto
        run: okteto login --token=${{ secrets.OKTETO_TOKEN }}
      - name: build and push new image
        run: okteto build -t registry.cloud.okteto.net/mr-exception/bell .
