name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push  
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_ID }}/bell:${{ github.sha }}
          push: false
      - name: Build
        id: docker_build
        run: docker build -t ${{ secrets.DOCKER_ID }}/bell:${{ github.sha }} .
      - name: Push
        id: docker_push
        run: docker push --disable-content-trust ${{ secrets.DOCKER_ID }}/bell:${{ github.sha }} .
      # - name: Build
      #   uses: okteto/actions/build@v1
      #   with:
      #     token: ${{ secrets.OKTETO_TOKEN }}
      #     tag: ${{ secrets.DOCKER_ID }}/bell:${{ github.sha }}
      # - name: Get Kubeconfig
      #   uses: okteto/actions/namespace@v1
      #   id: namespace
      #   with:
      #     token: ${{ secrets.OKTETO_TOKEN }}
      #     namespace: mr-exception
      # - name: Deploy and Wait
      #   uses: okteto/actions/deploy@v1
      #   env:
      #     KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
      #   with:
      #     namespace: mr-exception
      #     manifest: k8s.yml
      #     tag: ${{ secrets.DOCKER_USERNAME }}/bell:${{ github.sha }}
      #     waitOn: deployment/bell
      # - name: Verify
      #   uses: srt32/uptime@master
      #   with:
      #     url-to-hit: "https://bell-mr-exception.cloud.okteto.net"
      #     expected-statuses: "404"
