on: push
name: example
jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        namespace: mr-exception
        manifest: oktet.yaml
    - name: "Push changes"
      uses: okteto/push@master
      with:
        namespace: mr-exception
        name: bell
    # - name: "Build"
    #   uses: okteto/build@master
    #   with:
    #     tag: registry.cloud.okteto.net/mr-exception/bell:${{ github.sha }}