on: push
name: deploy
jobs:
  okteto:
    runs-on: ubuntu-latest
    steps:
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: "Push changes"
        uses: okteto/push@master
        with:
          namespace: mr-exception
          name: bell
    # - name: "Build"
    #   uses: okteto/build@master
    #   with:
    #     tag: registry.cloud.okteto.net/mr-exception/bell:${{ github.sha }}
