# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: salimondev 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          tags: salimondev/bell:${{ github.sha }}
          push: true
      
