# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to docker
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_ID }} 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          tags: ${{ secrets.DOCKER_ID }}/bell:${{ github.sha }}
          push: true
      
